use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::HashMap;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum NodeKind {
    Trigger,
    HotkeyTrigger,
    TimerTrigger,
    ManualTrigger,
    WindowTrigger,
    UiaElement,
    MouseOperation,
    MouseClick,
    MouseMove,
    MouseDrag,
    MouseWheel,
    MouseDown,
    MouseUp,
    KeyboardOperation,
    KeyboardKey,
    KeyboardInput,
    KeyboardDown,
    KeyboardUp,
    Shortcut,
    InputPresetReplay,
    Screenshot,
    WindowActivate,
    LaunchApplication,
    FileOperation,
    FileCopy,
    FileMove,
    FileDelete,
    RunCommand,
    PythonCode,
    ClipboardRead,
    ClipboardWrite,
    FileReadText,
    FileWriteText,
    ShowMessage,
    Delay,
    SystemOperation,
    PowerShutdown,
    PowerRestart,
    PowerSleep,
    PowerHibernate,
    PowerLock,
    PowerSignOut,
    SystemVolumeMute,
    SystemVolumeSet,
    SystemVolumeAdjust,
    SystemBrightnessSet,
    SystemWifiSwitch,
    SystemBluetoothSwitch,
    SystemNetworkAdapterSwitch,
    SystemTheme,
    SystemPowerPlan,
    SystemOpenSettings,
    GuiAgent,
    GuiAgentActionParser,
    Condition,
    Loop,
    WhileLoop,
    ImageMatch,
    OcrMatch,
    VarDefine,
    VarSet,
    VarMath,
    VarGet,
    ConstValue,
    JsonExtract,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkflowNode {
    pub id: String,
    pub label: String,
    pub kind: NodeKind,
    pub position_x: f64,
    pub position_y: f64,
    pub params: HashMap<String, Value>,
}
